// @generated by tools/wit_bindgen/generate.py. Do not hand-edit.

//! Generated host and guest bindings for the experimental `@0.0.4` WIT packages.

/// Workspace crate version that owns these experimental `@0.0.4` bindings (`0.1.0`).
pub const CRATE_VERSION: &str = "0.1.0";
/// Checked-in WIT package `finstack:ai-types@0.0.4`.
pub const AI_TYPES_PACKAGE: &str = "finstack:ai-types@0.0.4";
/// Checked-in WIT package `finstack:ai-host@0.0.4`.
pub const AI_HOST_PACKAGE: &str = "finstack:ai-host@0.0.4";
/// Checked-in WIT package `finstack:ai-toolset@0.0.4`.
pub const AI_TOOLSET_PACKAGE: &str = "finstack:ai-toolset@0.0.4";
/// Checked-in WIT package `finstack:ai-context@0.0.4`.
pub const AI_CONTEXT_PACKAGE: &str = "finstack:ai-context@0.0.4";
/// Worlds published by this experimental plugin alpha.
pub const PUBLISHED_PACKAGES: &[&str] = &[
    "finstack:ai-types@0.0.4",
    "finstack:ai-host@0.0.4",
    "finstack:ai-toolset@0.0.4",
    "finstack:ai-context@0.0.4",
];
/// Host imports granted by experimental plugin worlds. Linking them is not ambient WASI.
pub const HOST_IMPORTS: &[&str] = &[
    "finstack:ai-host/logging@0.0.4",
    "finstack:ai-host/blobs@0.0.4",
];
/// Guest exports of `toolset-plugin`.
pub const TOOLSET_WORLD_EXPORTS: &[&str] = &["toolset"];
/// Functions exported by the `toolset` interface.
pub const TOOLSET_FUNCS: &[&str] = &["list-tools", "call"];
/// Guest exports of `context-plugin`.
pub const CONTEXT_WORLD_EXPORTS: &[&str] = &["context-provider"];
/// Functions exported by the `context-provider` interface.
pub const CONTEXT_FUNCS: &[&str] = &["collect"];
/// Tokens that must not appear as nested-agent or lineage operations.
pub const FORBIDDEN_WORLD_TOKENS: &[&str] = &["agent", "session", "run", "lineage", "nested"];
/// WIT `call-context` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CallContext {
    /// WIT field `effect-id`.
    pub effect_id: String,
    /// WIT field `session-id`.
    pub session_id: String,
    /// WIT field `lane-id`.
    pub lane_id: String,
    /// WIT field `run-id`.
    pub run_id: String,
    /// WIT field `tenant-scope`.
    pub tenant_scope: String,
    /// WIT field `principal-issuer`.
    pub principal_issuer: String,
    /// WIT field `principal-subject`.
    pub principal_subject: String,
    /// WIT field `authorization-decision-id`.
    pub authorization_decision_id: String,
    /// WIT field `permitted-scopes`.
    pub permitted_scopes: Vec<String>,
    /// WIT field `budget-scope-id`.
    pub budget_scope_id: Option<String>,
    /// WIT field `deadline-unix-ms`.
    pub deadline_unix_ms: Option<i64>,
}
/// WIT `blob-ref` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BlobRef {
    /// WIT field `id`.
    pub id: String,
    /// WIT field `media-type`.
    pub media_type: String,
    /// WIT field `length`.
    pub length: u64,
    /// WIT field `digest`.
    pub digest: Option<String>,
}
/// WIT `plugin-error` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PluginError {
    /// WIT field `code`.
    pub code: String,
    /// WIT field `message`.
    pub message: String,
    /// WIT field `retryable`.
    pub retryable: bool,
}
/// WIT `tool-spec` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ToolSpec {
    /// WIT field `id`.
    pub id: String,
    /// WIT field `model-name`.
    pub model_name: String,
    /// WIT field `title`.
    pub title: String,
    /// WIT field `description`.
    pub description: String,
    /// WIT field `input-schema-json`.
    pub input_schema_json: Vec<u8>,
    /// WIT field `output-schema-json`.
    pub output_schema_json: Option<Vec<u8>>,
    /// WIT field `execution-mode`.
    pub execution_mode: String,
    /// WIT field `side-effect`.
    pub side_effect: String,
    /// WIT field `retry-safety`.
    pub retry_safety: String,
    /// WIT field `approval-policy-json`.
    pub approval_policy_json: Vec<u8>,
    /// WIT field `max-result-bytes`.
    pub max_result_bytes: u64,
    /// WIT field `metadata-json`.
    pub metadata_json: Vec<u8>,
}
/// WIT `tool-catalog` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ToolCatalog {
    /// WIT field `digest`.
    pub digest: String,
    /// WIT field `tools`.
    pub tools: Vec<ToolSpec>,
}
/// WIT `tool-result` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ToolResult {
    /// WIT field `content-json`.
    pub content_json: Vec<u8>,
    /// WIT field `is-error`.
    pub is_error: bool,
}
/// WIT `context-budget` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ContextBudget {
    /// WIT field `max-tokens`.
    pub max_tokens: u64,
    /// WIT field `max-bytes`.
    pub max_bytes: u64,
    /// WIT field `max-items`.
    pub max_items: u32,
}
/// WIT `context-query` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ContextQuery {
    /// WIT field `context`.
    pub context: CallContext,
    /// WIT field `request-json`.
    pub request_json: Vec<u8>,
    /// WIT field `budget`.
    pub budget: ContextBudget,
}
/// WIT `context-item` record generated from the checked-in v0.0.4 packages.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ContextItem {
    /// WIT field `item-json`.
    pub item_json: Vec<u8>,
    /// WIT field `blobs`.
    pub blobs: Vec<BlobRef>,
    /// WIT field `estimated-tokens`.
    pub estimated_tokens: u64,
    /// WIT field `bytes`.
    pub bytes: u64,
}
/// WIT `level` enum generated from the checked-in v0.0.4 packages.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Level {
    /// WIT case `trace`.
    Trace,
    /// WIT case `debug`.
    Debug,
    /// WIT case `info`.
    Info,
    /// WIT case `warn`.
    Warn,
    /// WIT case `error`.
    Error,
}
/// Generated host binding for WIT interface `logging`.
pub trait HostLogging {
    /// WIT function `log`.
    ///
    /// # Errors
    ///
    /// Returns [`PluginError`] when the binding rejects the call.
    fn log(&self, context: &CallContext, level: &Level, message: &str) -> Result<(), PluginError>;
}
/// Generated host binding for WIT interface `blobs`.
pub trait HostBlobs {
    /// WIT function `read`.
    ///
    /// # Errors
    ///
    /// Returns [`PluginError`] when the binding rejects the call.
    fn read(
        &self,
        context: &CallContext,
        reference: &BlobRef,
        offset: u64,
        max_bytes: u64,
    ) -> Result<Vec<u8>, PluginError>;
}
/// Generated guest binding for WIT interface `toolset`.
pub trait GuestToolset {
    /// WIT function `list-tools`.
    ///
    /// # Errors
    ///
    /// Returns [`PluginError`] when the binding rejects the call.
    fn list_tools(&self) -> Result<ToolCatalog, PluginError>;
    /// WIT function `call`.
    ///
    /// # Errors
    ///
    /// Returns [`PluginError`] when the binding rejects the call.
    fn call(
        &self,
        context: &CallContext,
        tool_id: &str,
        args_json: &[u8],
    ) -> Result<ToolResult, PluginError>;
}
/// Generated guest binding for WIT interface `context-provider`.
pub trait GuestContextProvider {
    /// WIT function `collect`.
    ///
    /// # Errors
    ///
    /// Returns [`PluginError`] when the binding rejects the call.
    fn collect(&self, query: &ContextQuery) -> Result<Vec<ContextItem>, PluginError>;
}
